#include "sdw_enums.h"
#include "../sdk/dinput.h"

#define SDW_MEMBERS_InputDevice InputDevice();                                  /* InputDevice_Construct */
#define SDW_MEMBERS_Mouse Mouse(u16 buttonCount, D3DApp *app, HRESULT *result); /* Mouse_Construct */
#include "sdw_classes.h"
#include "../sdk/crt.h"
#include "../sdk/win32.h"

/* ======================================================================== Mouse */

/* The mouse through SDL3 (src/platform/platform.h). The axes are the motion since the previous
 * frame, as DirectInput's relative mickeys were (not rounded to a multiple of 8, which lost slow motion). */
#include "../platform/platform.h"

Mouse::Mouse(u16 buttonCount, D3DApp *app, HRESULT *result)
{
    if (buttonCount > 4)
        AllocButtons(4, app);
    else
        AllocButtons(buttonCount, app);
    deviceKind = INPUTDEV_MOUSE;
    isDigital = 0;
    pDevice = NULL;
    *result = S_OK;
}

Mouse::~Mouse() {}

long Mouse::SetAcquired(u8 acquire)
{
    acquired = acquire == 1;
    return 0;
}

long Mouse::Update()
{
    u8 buttons[4];
    u16 i;
    if (acquired != 1)
        return E_FAIL;
    Platform_ReadMouse(&rawX, &rawY, &rawZ, buttons);
    for (i = 0; i < buttonCount; i++)
        buttonDown[i] = buttons[i];
    InputDevice::Update();
    return 0;
}

/* Mouse_ScalarDeletingDtor: generated by the compiler from the virtual destructor. */
