/*
 * Shared declarations: input_device.h next to this file.
 */
#include "input_device.h"
#include "sdw_enums.h"
#include "../sdk/dinput.h"

IDirectInputDevice8A *g_pEnumJoystickDevice; /* the device DI_JoystickAxisEnumCallback configures */

/* ======================================================================== Joystick, */

/* The controller chosen in the launcher (D3DApp::joystickIndex, in SDL's order) through SDL3
 * (src/platform/platform.h), with DirectInput's axis range and button numbers. */
#include "../platform/platform.h"

Joystick::Joystick(u16 buttonCount, D3DApp *app, HRESULT *result)
{
    if (buttonCount > 0x20)
        AllocButtons(0x20, app);
    else
        AllocButtons(buttonCount, app);
    deviceKind = INPUTDEV_JOYSTICK;
    pDevice = NULL;
    *result = E_FAIL;
    if (Platform_OpenJoystick(pApp->joystickIndex)) {
        isDigital = 0;
        *result = S_OK;
    }
}

Joystick::~Joystick()
{
    Platform_CloseJoystick();
}

long Joystick::SetAcquired(u8 acquire)
{
    acquired = acquire == 1;
    return 0;
}

/* the axes (left stick, and the right stick the original never read) rounded down to a multiple of 8, as the original */
long Joystick::Update()
{
    s32 axes[5];
    if (acquired != 1 || !Platform_ReadJoystick(axes, buttonDown, buttonCount))
        return E_FAIL; /* gone: the input manager hands over to the keyboard */
    rawX = (axes[0] >> 3) << 3;
    rawY = (axes[1] >> 3) << 3;
    rawZ = (axes[2] >> 3) << 3;
    rawRX = (axes[3] >> 3) << 3; /* the right stick */
    rawRY = (axes[4] >> 3) << 3;
    InputDevice::Update();
    return 0;
}

/* EnumObjects callback for the joystick's axes: range -0xffff..0xffff. Stops the enumeration on failure. */
BOOL __stdcall DI_JoystickAxisEnumCallback(const DIDEVICEOBJECTINSTANCEA *doi, void *ref)
{
    BOOL ret;
    DIPROPRANGE diprg;
    diprg.diph.dwSize = sizeof(DIPROPRANGE);
    diprg.diph.dwHeaderSize = sizeof(DIPROPHEADER);
    diprg.diph.dwHow = DIPH_BYID;
    diprg.diph.dwObj = doi->dwType;
    diprg.lMin = -0xffff;
    diprg.lMax = 0xffff;
    if (g_pEnumJoystickDevice->SetProperty(DIPROP_RANGE, &diprg.diph) < 0)
        ret = DIENUM_STOP;
    else
        ret = DIENUM_CONTINUE;
    return ret;
}

/* Joystick_ScalarDeletingDtor: generated by the compiler from the virtual destructor. */
