/*
 * Shared declarations: input_device.h next to this file.
 */
#include "input_device.h"
#include "sdw_enums.h"
#include "../sdk/dinput.h"

/* The keyboard comes from SDL3 (src/platform/platform.h), still indexed by DirectInput scan code, so
 * the bindings, the saved configurations and the .BSC files keep their codes. */
#include "../platform/platform.h"

/* the key's name (the keyboard's objects are its scan codes) */
u32 InputDevice::GetObjectName(u32 diObjOffset, char *out)
{
    return Platform_KeyName(diObjOffset, out, 0x40) ? 1 : 0;
}

Keyboard::Keyboard(u16 buttonCount, D3DApp *app, HRESULT *result)
{
    AllocButtons(buttonCount, app);
    deviceKind = INPUTDEV_KEYBOARD;
    isDigital = 1;
    pDevice = NULL;
    *result = buttonCount >= 0x100 ? S_OK : E_FAIL; /* SDL's state is read by scan code: all 256 are needed */
    KB_AXISKEY(KB_AXIS_X_NEG) = DIK_LEFT;
    KB_AXISKEY(KB_AXIS_X_POS) = DIK_RIGHT;
    KB_AXISKEY(KB_AXIS_Y_NEG) = DIK_UP;
    KB_AXISKEY(KB_AXIS_Y_POS) = DIK_DOWN;
    KB_AXISKEY(KB_AXIS_Z_NEG) = DIK_NEXT;
    KB_AXISKEY(KB_AXIS_Z_POS) = DIK_PRIOR;
}

Keyboard::~Keyboard() {}

long Keyboard::SetAcquired(u8 acquire)
{
    acquired = acquire == 1;
    return 0;
}

/* the keys, then the axes from the axis keys: +1 when only the positive key is held, -1 when only the
 * negative one is, else 0. */
long Keyboard::Update()
{
    if (acquired != 1)
        return E_FAIL;
    Platform_ReadKeyboard(buttonDown);
    InputDevice::Update();
    if (buttonDown[KB_AXISKEY(KB_AXIS_X_POS)] && !buttonDown[KB_AXISKEY(KB_AXIS_X_NEG)])
        axisX = 1.0f;
    else if (!buttonDown[KB_AXISKEY(KB_AXIS_X_POS)] && buttonDown[KB_AXISKEY(KB_AXIS_X_NEG)])
        axisX = -1.0f;
    else
        axisX = 0.0f;
    if (buttonDown[KB_AXISKEY(KB_AXIS_Y_POS)] && !buttonDown[KB_AXISKEY(KB_AXIS_Y_NEG)])
        axisY = 1.0f;
    else if (!buttonDown[KB_AXISKEY(KB_AXIS_Y_POS)] && buttonDown[KB_AXISKEY(KB_AXIS_Y_NEG)])
        axisY = -1.0f;
    else
        axisY = 0.0f;
    if (buttonDown[KB_AXISKEY(KB_AXIS_Z_POS)] && !buttonDown[KB_AXISKEY(KB_AXIS_Z_NEG)])
        axisZ = 1.0f;
    else if (!buttonDown[KB_AXISKEY(KB_AXIS_Z_POS)] && buttonDown[KB_AXISKEY(KB_AXIS_Z_NEG)])
        axisZ = -1.0f;
    else
        axisZ = 0.0f;
    return 0;
}

/* replaces the six axis keys (no callers in the shipped build). */
void Keyboard::SetAxisKeys(u16 xNeg, u16 xPos, u16 yNeg, u16 yPos, u16 zNeg, u16 zPos)
{
    KB_AXISKEY(KB_AXIS_X_NEG) = xNeg;
    KB_AXISKEY(KB_AXIS_X_POS) = xPos;
    KB_AXISKEY(KB_AXIS_Y_NEG) = yNeg;
    KB_AXISKEY(KB_AXIS_Y_POS) = yPos;
    KB_AXISKEY(KB_AXIS_Z_NEG) = zNeg;
    KB_AXISKEY(KB_AXIS_Z_POS) = zPos;
}

/* Keyboard_ScalarDeletingDtor: generated by the compiler from the virtual destructor. */
