"""Compiles the SDL3 renderer's shaders into src/render/sdl3/sdl3_shaders.h.

The header is committed, so building the game needs no shader compiler; run this after editing
src/render/sdl3/shaders/game.hlsl or game.metal:

    py -3 tools/sdl3_shaders.py [--fxc PATH] [--dxc PATH]

  fxc  the Windows SDK's (found under "Windows Kits\\10\\bin" when not given): DXBC shader model 5.1, for Direct3D 12
  dxc  one built with SPIR-V output (the DirectXShaderCompiler releases on GitHub, or the Vulkan SDK's; the Windows
       SDK's has none): SPIR-V, for Vulkan
The Metal source is embedded as text (SDL compiles MSL at run time).
"""
import argparse
import glob
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADER_DIR = os.path.join(ROOT, "src", "render", "sdl3", "shaders")
OUT = os.path.join(ROOT, "src", "render", "sdl3", "sdl3_shaders.h")


def find_fxc():
    found = sorted(glob.glob(r"C:\Program Files (x86)\Windows Kits\10\bin\10.*\x64\fxc.exe"))
    return found[-1] if found else shutil.which("fxc")


def run(cmd):
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode:
        sys.exit("failed: %s\n%s%s" % (" ".join(cmd), result.stdout, result.stderr))


def c_bytes(name, data):
    lines = ["static const unsigned char %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 20):
        lines.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 20]) + ",")
    lines.append("};")
    return "\n".join(lines)


def c_string(name, text):
    lines = ["static const char %s[] =" % name]
    for line in text.splitlines():
        lines.append('    "%s\\n"' % line.replace("\\", "\\\\").replace('"', '\\"'))
    lines.append(";")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--fxc", default=os.environ.get("FXC") or find_fxc())
    parser.add_argument("--dxc", default=os.environ.get("DXC") or shutil.which("dxc"))
    args = parser.parse_args()
    if not args.fxc or not args.dxc:
        sys.exit("need fxc and a SPIR-V capable dxc (--fxc / --dxc)")

    hlsl = os.path.join(SHADER_DIR, "game.hlsl")
    blobs = []
    with tempfile.TemporaryDirectory() as tmp:
        for stage, entry, fxc_profile, dxc_profile in (("vs", "VSMain", "vs_5_1", "vs_6_0"),
                                                      ("ps", "PSMain", "ps_5_1", "ps_6_0")):
            dxbc = os.path.join(tmp, stage + ".dxbc")
            spirv = os.path.join(tmp, stage + ".spv")
            run([args.fxc, "/nologo", "/O3", "/T", fxc_profile, "/E", entry, "/Fo", dxbc, hlsl])
            run([args.dxc, "-nologo", "-O3", "-spirv", "-fspv-target-env=vulkan1.0", "-T", dxc_profile, "-E", entry,
                 "-Fo", spirv, hlsl])
            with open(dxbc, "rb") as f:
                blobs.append(c_bytes("g_sdl3_%s_dxbc" % stage, f.read()))
            with open(spirv, "rb") as f:
                blobs.append(c_bytes("g_sdl3_%s_spirv" % stage, f.read()))
    with open(os.path.join(SHADER_DIR, "game.metal")) as f:
        blobs.append(c_string("g_sdl3_msl", f.read()))

    with open(OUT, "w", newline="\n") as f:
        f.write("/* GENERATED by tools/sdl3_shaders.py from src/render/sdl3/shaders/ - do not edit by hand. */\n")
        f.write("#ifndef SDL3_SHADERS_H\n#define SDL3_SHADERS_H\n\n")
        f.write("\n\n".join(blobs))
        f.write("\n\n#endif\n")
    print("wrote", os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
